-- require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
-- require "user.telescope"
-- require "user.gitsigns"
-- require "user.autopairs"
-- require "user.toggleterm"
require "user.lualine"
require "user.nvim-tree"
-- require "user.alpha"
require "user.whichkey"
