-- require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.telescope"
require "user.treesitter"
require "user.gitsigns"
-- require "user.autopairs"
require "user.comment"
-- require "user.toggleterm" -- used with lazygit
require "user.lualine"
require "user.nvim-tree"
require "user.alpha"
require "user.autocommands"
require "user.whichkey"
